### ISSUE TITLE
Adding representation for an ideographic space

### ISSUE THREAD

**Issue by mikelothers** [silnrsi/font-charsym#1]
I think that the font looks great, Victor. Thank you!

One character that we meant to request in the font is an ideographic space. 

Attached is an SVG of a representation that we were thinking of using. Does it look reasonable to you?
![IdeographicSpace](https://github.com/silnrsi/font-symchar/assets/4229839/465645f8-8bda-4983-8012-845b493fa811)

**Comment by jvgaultney** [comment]
I can add that but it may be a few days as I now have other priorities. How critical is it? Does this stop you from using the font?

Also - that symbol is missing the middle dot that we seemed to agree was important to have in 'space' symbols. I'm happy to do what you have suggested - I just wanted to be sure you'd thought through the visual semantics.

**Comment by ianhewubs** [comment]
Good point Victor. I'm checking with a Chinese consultant on the acceptability of the following alternative character:
![image](https://github.com/silnrsi/font-symchar/assets/57722808/743badb8-30ad-46fd-a787-6bab955e08f2)

**Comment by mikelothers** [comment]
Thanks for that feedback, Victor. Ian's alternative looks like an improvement, if it is accepted by the consultant. See his message below.

Adding the ideographic space is not time critical for us. We are still able to move forward with the font that you have provided.

**Comment by jvgaultney** [comment]
Thanks that's helpful - I'm corresponding directly with Ian regarding the design options.

**Comment by jvgaultney** [comment]
Added
