### ISSUE TITLE
back_rev_1

### ISSUE THREAD

**Issue by parthakr** [silnrsi/font-charsym#2]
back_rev hollow shape needs to be added similar to back_1

![Screenshot 2023-12-09 at 9 34 11 AM](https://github.com/silnrsi/font-symchar/assets/22424042/95997938-54d1-4899-97c0-f7a7692f4d1f)

**Comment by jahorton** [comment]
Keyman team would like this eventually.  No rush on our end yet, though.

https://github.com/keymanapp/keyman/pull/10221#issuecomment-1851244289

**Comment by jvgaultney** [comment]
From the linked discussion this does sound like it's not urgent, so we will probably wait a few months or until some other more urgent need requires a new release. If this does become urgent we can turn it around quickly - just let us know.

**Comment by mcdurdin** [comment]
I think we'll aim to address this in Keyman 18.0 in the 2024 cycle. It's not urgent; we won't be onto this until March 2024 at earliest.

**Comment by jvgaultney** [comment]
back_rev_1 added in version 4.100 at U+E06A
